mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  datasource:
    username: root
#    username: dev
    password: 123456
    url: jdbc:mysql://192.168.111.59:3306/appo?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://192.168.19.168:3306/appo?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    #以下是durid配置
    initialSize: 5
    minIdle: 5
    maxAtive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    database: 0
#    host: 127.0.0.1
    host: 192.168.111.59
#    host: 192.168.19.168
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    connect-timeout: 1200


#Redis